### ISSUE TITLE
Question about the setup on https://www.factual.com/blog/docker-mesos-marathon-and-the-end-of-pets

### ISSUE THREAD

**Issue by ksrinivs64** [bfs/docker-mesos-master#1]
Hi I am a newbie to mesos, marathon and docker and had a question about your set up on the blog.  Is there a reason why the mesos-slave is not set up as a docker container as well?  Thanks in advance for answering my question.

**Comment by bfs** [comment]
It might be possible, but the goal is to allocate/manage the metal resources via mesos, which would be harder if other services run on the same box.  In that sense, there's not much downside to running "natively" nor much upside to running inside docker.
